# Generated by Django 4.1.3 on 2024-06-07 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(blank=True, default=False, upload_to='')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, choices=[('organic', 'Organic'), ('inorganic', 'Inorganic')], max_length=25, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy')], max_length=25, null=True)),
                ('classification', models.CharField(blank=True, choices=[('organic', 'Organic'), ('inorganic', 'Inorganic')], max_length=25, null=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_inorganic', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Products.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
