# Generated by Django 4.1.3 on 2024-06-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='cart_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
